### ISSUE TITLE
Secret manager is incompatible with OIDC web app

### ISSUE THREAD

**Issue by manuelbl** [quarkiverse/quarkus-google-cloud-services#109]
Using the Secret Manager extension to specify the client credential for an OIDC web application is a natural fit. Unfortunately, it does not work. It throws an exception at startup (see below).

It looks like a problem with the initialization order. But I was unable to resolve it.

A complete example has been attached. It has been generated with https://code.quarkus.io/?e=oidc&e=resteasy-qute. The only additions are in `pom.xml` (addition of `quarkus-google-cloud-secret-manager`) and in *application.properties* (see below).

To reproduce the bug:
- Build the attached project and start it

It's not even necessary specify a valid IAM URL or create a secret in the Secret Manager. The app does not get that far. With a hard-coded credentials (and proper URLs), the app works.

[oidc-gcp.zip](https://github.com/quarkiverse/quarkus-google-cloud-services/files/6352420/oidc-gcp.zip)

*application.properties*:
```properties
quarkus.oidc.application-type=web_app
quarkus.oidc.auth-server-url=https://some.keycloak/auth/realms/myrealm
quarkus.oidc.client-id=my-client-id
quarkus.oidc.credentials.client-secret.value=${sm//keycloak-credential}
quarkus.http.auth.permission.authenticated.paths=/qute/quarks/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.arc.unremovable-types=com.google.cloud.secretmanager.v1.SecretManagerServiceClient
quarkus.google.cloud.access-token-enabled=false
```

**Exception**:

```text
ERROR: Failed to start application (with profile dev)
javax.enterprise.inject.CreationException: Config root [io.quarkiverse.googlecloudservices.common.GcpConfiguration] with config phase [RUN_TIME] not initialized yet.
	at io.quarkiverse.googlecloudservices.common.GcpConfiguration_f5f0cfc0930d359f64931c3293f018103e1bfca6_Synthetic_Bean.create(GcpConfiguration_f5f0cfc0930d359f64931c3293f018103e1bfca6_Synthetic_Bean.zig:112)
	at io.quarkiverse.googlecloudservices.common.GcpConfiguration_f5f0cfc0930d359f64931c3293f018103e1bfca6_Synthetic_Bean.get(GcpConfiguration_f5f0cfc0930d359f64931c3293f018103e1bfca6_Synthetic_Bean.zig:146)
	at io.quarkiverse.googlecloudservices.common.GcpConfiguration_f5f0cfc0930d359f64931c3293f018103e1bfca6_Synthetic_Bean.get(GcpConfiguration_f5f0cfc0930d359f64931c3293f018103e1bfca6_Synthetic_Bean.zig:169)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.create(SecretManagerProducer_Bean.zig:244)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.create(SecretManagerProducer_Bean.zig:327)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ClientProxy.arc$delegate(SecretManagerProducer_ClientProxy.zig:67)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ClientProxy.arc_contextualInstance(SecretManagerProducer_ClientProxy.zig:82)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.create(SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.zig:186)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.create(SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.zig:204)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.get(SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.zig:236)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.get(SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.zig:252)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:430)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:443)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:413)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:222)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.config.SecretManagerClientProvider.get(SecretManagerClientProvider.java:18)
	at io.quarkiverse.googlecloudservices.secretmanager.runtime.config.SecretManagerConfigSource.getValue(SecretManagerConfigSource.java:40)
	at io.smallrye.config.ConfigValueConfigSourceWrapper.getConfigValue(ConfigValueConfigSourceWrapper.java:20)
	at io.smallrye.config.SmallRyeConfigSourceInterceptor.getValue(SmallRyeConfigSourceInterceptor.java:26)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfigSourceInterceptor.getValue(SmallRyeConfigSourceInterceptor.java:27)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfigSourceInterceptor.getValue(SmallRyeConfigSourceInterceptor.java:27)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfigSourceInterceptor.getValue(SmallRyeConfigSourceInterceptor.java:27)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfigSourceInterceptor.getValue(SmallRyeConfigSourceInterceptor.java:27)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfigSourceInterceptor.getValue(SmallRyeConfigSourceInterceptor.java:27)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SecretKeysConfigSourceInterceptor.getValue(SecretKeysConfigSourceInterceptor.java:22)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.RelocateConfigSourceInterceptor.getValue(RelocateConfigSourceInterceptor.java:26)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.ProfileConfigSourceInterceptor.getValue(ProfileConfigSourceInterceptor.java:70)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:26)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.lambda$getValue$0(ExpressionConfigSourceInterceptor.java:38)
	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:37)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:18)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:253)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:210)
	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$oidc$common$runtime$OidcCommonConfig$Credentials$Secret(Config.zig:40353)
	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$oidc$common$runtime$OidcCommonConfig$Credentials(Config.zig:40275)
	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$oidc$OidcTenantConfig(Config.zig:38217)
	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$oidc$runtime$OidcConfig(Config.zig:64922)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1900)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:521)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by loicmathieu** [comment]
So the issue is that you configure the OIDC with a config key from the service manager via
```
quarkus.oidc.credentials.client-secret.value=${sm//keycloak-credential}
```
When removing this line, the application starts.
This is tricky, I'll have a look and see what we can do.

**Comment by manuelbl** [comment]
Yes, that's the core config line.

The application starts if either a hard coded value is inserted or the line is removed and the value is injected as an environment variable.

I've also tried to to use a startup event to force an earlier initialization. But it turns out, even that isn't early enough. So I'm not surprised it's tricky to solve.
