### ISSUE TITLE
Upgrade to latest version of quarkus of 1.13.x to avoid build error

### ISSUE THREAD

**Issue by mswiderski** [quarkiverse/quarkus-google-cloud-services#134]
Would it be possible to upgrade quarkus to version at least 1.13.3 to avoid following error

````
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.2.Final:build (default) on project google-cloud-run-pubsub: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: java.lang.IllegalAccessError: class io.quarkus.deployment.index.IndexingUtil tried to access private field io.quarkus.bootstrap.classloading.JarClassPathElement.JAVA_VERSION (io.quarkus.deployment.index.IndexingUtil is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @297ffaa7; io.quarkus.bootstrap.classloading.JarClassPathElement is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @6aa5974e)
[ERROR] 	at io.quarkus.deployment.index.IndexingUtil.indexJar(IndexingUtil.java:76)
[ERROR] 	at io.quarkus.deployment.index.IndexingUtil.indexJar(IndexingUtil.java:59)
[ERROR] 	at io.quarkus.deployment.index.IndexingUtil.indexJar(IndexingUtil.java:40)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep$1.apply(ApplicationArchiveBuildStep.java:268)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep$1.apply(ApplicationArchiveBuildStep.java:264)
[ERROR] 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.handleJarPath(ApplicationArchiveBuildStep.java:264)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.indexPath(ApplicationArchiveBuildStep.java:180)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.addMarkerFilePaths(ApplicationArchiveBuildStep.java:223)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.scanForOtherIndexes(ApplicationArchiveBuildStep.java:118)
[ERROR] 	at io.quarkus.deployment.index.ApplicationArchiveBuildStep.build(ApplicationArchiveBuildStep.java:96)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
````

This problem happens due to the `quarkus-google-cloud-services` declares 1.13.0 of quarkus but there was a change (https://github.com/quarkusio/quarkus/commit/dd9262e2ed6aaf400eb89b0e09df8babd1bf010e) that makes it fail with above error during build.

I ran into this issue when having quarkus app with version `1.13.4` and including the `0.7.0` of `quarkus-google-cloud-pubsub`

A workaround was to exclude any of the `io.quarkus` dependencies like this

````
    <dependency>
      <groupId>io.quarkiverse.googlecloudservices</groupId>
      <artifactId>quarkus-google-cloud-pubsub</artifactId>
      <version>0.7.0</version>
      <exclusions>
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
````

**Comment by loicmathieu** [comment]
Which BOM did you declare first? The Quarkus one should always comes first as the versions should be takes from it.

**Comment by mswiderski** [comment]
I have only quarkus bom and then the dependency of `quarkus-google-cloud-pubsub` without bom of the quarkiverse.

**Comment by loicmathieu** [comment]
Even without the quarkiverse BOM, the includion of the Quarkus BOM first should pull the right dependencies, can you create a small reproducer so I can have a look ?
You can zip it and attache in the issue or give me the link of a Github repo.

**Comment by mswiderski** [comment]
I will work on smaller thing that what I have right now and see if there is something that can show the issue. Thanks for looking into that.

While testing it out I noticed that when running in native mode I got this error

````
2021-06-21 07:38:24,745 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-2) HTTP Request to / failed, error id: 70a7e0cd-7233-416e-8a74-409646537ded-6: io.quarkus.funqy.runtime.ApplicationException: java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Provider io.grpc.netty.NettyChannelProvider not found
2021-06-21 09:38:24.745 CEST at io.quarkus.funqy.runtime.FunctionInvoker.invoke(FunctionInvoker.java:131)
2021-06-21 09:38:24.745 CEST at io.quarkus.funqy.runtime.bindings.knative.events.VertxRequestHandler.dispatch(VertxRequestHandler.java:565)
2021-06-21 09:38:24.745 CEST at io.quarkus.funqy.runtime.bindings.knative.events.VertxRequestHandler.lambda$processCloudEvent$5(VertxRequestHandler.java:397)
2021-06-21 09:38:24.745 CEST at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
2021-06-21 09:38:24.745 CEST at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
2021-06-21 09:38:24.745 CEST at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2021-06-21 09:38:24.745 CEST at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2021-06-21 09:38:24.745 CEST at java.lang.Thread.run(Thread.java:834)
2021-06-21 09:38:24.745 CEST at org.jboss.threads.JBossThread.run(JBossThread.java:501)
2021-06-21 09:38:24.745 CEST at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
2021-06-21 09:38:24.745 CEST at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
2021-06-21 09:38:24.745 CEST Caused by: java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Provider io.grpc.netty.NettyChannelProvider not found
2021-06-21 09:38:24.745 CEST at java.util.ServiceLoader.fail(ServiceLoader.java:589)
2021-06-21 09:38:24.745 CEST at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
2021-06-21 09:38:24.745 CEST at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
2021-06-21 09:38:24.745 CEST at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
2021-06-21 09:38:24.745 CEST at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
````

Have you seen that before? I don't want to create too many issues and I don't see GitHub discussions enabled here that might be good place to take this up instead of new issue.

**Comment by mswiderski** [comment]
@loicmathieu I found the issue and it was on my end, one of the properties was setting quarkus version to 1.13.2 and that affected the maven plugin. So this is non-issue - sorry for the trouble.

**Comment by loicmathieu** [comment]
@mswiderski great that you fixed the issue !
For the netty issue, if it still occurs, please open another issue with a reproducer.

**Comment by mswiderski** [comment]
all issues are gone now, thanks a lot for your help @loicmathieu
