### ISSUE TITLE
Wrong BuildStep order in generated ApplicationImpl when using SecretManager extension

### ISSUE THREAD

**Issue by henriwi** [quarkiverse/quarkus-google-cloud-services#358]
We have a small Quarkus app where we use the `quarkus-google-cloud-secret-manager` to fetch a secret from GCP Secret Manager. This works fine, but the application fails sporadically with the following message: 

```
2022-12-05T19:45:56+01:00 Dec 05, 2022 6:45:56 PM io.quarkus.runtime.ApplicationLifecycleManager run
2022-12-05T19:45:56+01:00 ERROR: Failed to start application (with profile prod)
2022-12-05T19:45:56+01:00 java.lang.NullPointerException: Cannot read field "serviceAccountLocation" because "gcpConfiguration" is null
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.common.GcpCredentialProducer.googleCredential(GcpCredentialProducer.java:46)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.common.GcpCredentialProducer_ProducerMethod_googleCredential_f50c1039bd62c63834aaa61a686a2c22210490cc_Bean.create(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.common.GcpCredentialProducer_ProducerMethod_googleCredential_f50c1039bd62c63834aaa61a686a2c22210490cc_Bean.create(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.common.GcpCredentialProducer_ProducerMethod_googleCredential_f50c1039bd62c63834aaa61a686a2c22210490cc_Bean.get(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.common.GcpCredentialProducer_ProducerMethod_googleCredential_f50c1039bd62c63834aaa61a686a2c22210490cc_Bean.get(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.create(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.create(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.get(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.get(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.create(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.create(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.get(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.get(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:476)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:489)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:460)
2022-12-05T19:45:56+01:00 	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:224)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.config.SecretManagerClientProvider.get(SecretManagerClientProvider.java:18)
2022-12-05T19:45:56+01:00 	at io.quarkiverse.googlecloudservices.secretmanager.runtime.config.SecretManagerConfigSource.getValue(SecretManagerConfigSource.java:46)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.ConfigValueConfigSourceWrapper.getConfigValue(ConfigValueConfigSourceWrapper.java:20)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfigSources.getValue(SmallRyeConfigSources.java:29)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SecretKeysConfigSourceInterceptor.getValue(SecretKeysConfigSourceInterceptor.java:24)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.RelocateConfigSourceInterceptor.getValue(RelocateConfigSourceInterceptor.java:25)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.RelocateConfigSourceInterceptor.getValue(RelocateConfigSourceInterceptor.java:25)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.ProfileConfigSourceInterceptor.getValue(ProfileConfigSourceInterceptor.java:57)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:50)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.ExpressionConfigSourceInterceptor.access$000(ExpressionConfigSourceInterceptor.java:22)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.ExpressionConfigSourceInterceptor$1.accept(ExpressionConfigSourceInterceptor.java:66)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.ExpressionConfigSourceInterceptor$1.accept(ExpressionConfigSourceInterceptor.java:63)
2022-12-05T19:45:56+01:00 	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
2022-12-05T19:45:56+01:00 	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
2022-12-05T19:45:56+01:00 	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:63)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:42)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.FallbackConfigSourceInterceptor.getValue(FallbackConfigSourceInterceptor.java:24)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:324)
2022-12-05T19:45:56+01:00 	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:230)
2022-12-05T19:45:56+01:00 	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$datasource$runtime$DataSourceRuntimeConfig(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkus.runtime.generated.Config.initGroup$io$quarkus$datasource$runtime$DataSourcesRuntimeConfig(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2022-12-05T19:45:56+01:00 	at io.quarkus.runtime.Application.start(Application.java:101)
2022-12-05T19:45:56+01:00 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
2022-12-05T19:45:56+01:00 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
2022-12-05T19:45:56+01:00 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
2022-12-05T19:45:56+01:00 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:123)
2022-12-05T19:45:56+01:00 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2022-12-05T19:45:56+01:00 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-12-05T19:45:56+01:00 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-12-05T19:45:56+01:00 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-12-05T19:45:56+01:00 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-12-05T19:45:56+01:00 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
2022-12-05T19:45:56+01:00 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
2022-12-05T19:45:56+01:00 
"
```

We have not been able to consistently reproduce the issue, but the failure occurs maybe once per 4-5 builds. But we have been able to find a difference in the generated `io.quarkus.runner.ApplicationImpl` class when looking at a failing version and a successful version. This is an excerpt from the generated class in a successful build:

```
 protected final void doStart(String[] var1) {
...
       try {
            StepTiming.configureStart();
            ((StartupTask)(new VertxCoreProcessor.createVertxThreadFactory1036986175())).deploy(var2);
            StepTiming.printStepTime(var2);
            ((StartupTask)(new BootstrapConfigSetup())).deploy(var2);
            StepTiming.printStepTime(var2);
            ((StartupTask)(new CommonBuildSteps.configure370655783())).deploy(var2);
            StepTiming.printStepTime(var2);
            ((StartupTask)(new SecretManagerBuildSteps.configure164105874())).deploy(var2);
            StepTiming.printStepTime(var2);
```

And this is from a failed build:

```
 protected final void doStart(String[] var1) {
  ...
   try {
      StepTiming.configureStart();
      ((StartupTask)(new VertxCoreProcessor.createVertxContextHandlers784870001())).deploy(var2);
      StepTiming.printStepTime(var2);
      ((StartupTask)(new VertxCoreProcessor.createVertxThreadFactory1036986175())).deploy(var2);
      StepTiming.printStepTime(var2);
      ((StartupTask)(new BootstrapConfigSetup())).deploy(var2);
      StepTiming.printStepTime(var2);
      ((StartupTask)(new SecretManagerBuildSteps.configure164105874())).deploy(var2);
      StepTiming.printStepTime(var2);
      ((StartupTask)(new RuntimeConfigSetup())).deploy(var2);
      StepTiming.printStepTime(var2);
      ...
      ((StartupTask)(new CommonBuildSteps.configure370655783())).deploy(var2);
...
```

What we have noticed is that in the failing build, the **SecretManagerBuildSteps** is called **before** **CommonBuildSteps**, while in the successful build, **SecretManagerBuildSteps** is called **after** **CommonBuildSteps**. 

The CommonBuildSteps seems to actually trigger the `GcpCredentialRecorder.configure` method which in turn sets the bootstrapConfig in the `GcpConfigHolder` class, which makes the field non-null when retrieving the bootstrapConfig in `GcpCredentialProducer:45`

Our application configuration consists of only one secret and no other configurations relevant for the secret manager extension has been applied:
```
%prod.quarkus.datasource.password=${sm//<secret-name>}
```

The google project id and credentials file location are sent in during startup using the following environment variables:
```
GOOGLE_CLOUD_PROJECT=<project-id>
GOOGLE_APPLICATION_CREDENTIALS=<path-to-credentials-file>
```

We have looked at some of the other issues where the same error message has been encountered (https://github.com/quarkiverse/quarkus-google-cloud-services/issues/209 and https://github.com/quarkiverse/quarkus-google-cloud-services/issues/298), but have not been able to fix the issue.

**Comment by henriwi** [comment]
Thanks for the quick reply! Yes, the non-deterministic behaviour makes this very hard :) Great if you could have a look and see if you are able to fix this/make the build step order deterministic.

And let me know if you need some additional debug information from our setup.

**Comment by loicmathieu** [comment]
@henriwi if you can try #361 it would be great.

**Comment by henriwi** [comment]
@loicmathieu I've tried building our application using the version from #361 and it seems to work as expected 👍 Difficult to say for sure due to the non-deterministic behaviour of course, but all the builds I've done results in the order being correct (`CommonBuildSteps` before `SecretManagerBuildSteps`) in `io.quarkus.runner.ApplicationImpl`

What do you think of releasing this fix in the near future?

**Comment by loicmathieu** [comment]
I'll merge it now and it will be released in the next release, should be next week for Quarkus 2.15.
