### ISSUE TITLE
Google Cloud Logging

### ISSUE THREAD

**Issue by zZHorizonZz** [quarkiverse/quarkus-google-cloud-services#421]
I have noticed that when you try to use google cloud logging there is probably something wrong with the configuration. Precisely with project-id configuration which doesn't seem like it gets read? I noticed this when I tried it to use in the internal project and also in build logs this [job](https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/4762563265/jobs/8464934801?pr=420).

```
LogManager error of type WRITE_FAILURE: Failed to publish record to GCP
java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:304)
	at com.google.cloud.logging.LoggingOptions.<init>(LoggingOptions.java:118)
	at com.google.cloud.logging.LoggingOptions$Builder.build(LoggingOptions.java:112)
	at com.google.cloud.logging.LoggingOptions.getDefaultInstance(LoggingOptions.java:57)
	at io.quarkiverse.googlecloudservices.logging.runtime.cdi.LoggingProducer.create(LoggingProducer.java:39)
	at io.quarkiverse.googlecloudservices.logging.runtime.cdi.LoggingProducer_ProducerMethod_create_43cdc485b040e9e622e14fa50960c6f67837b748_Bean.doCreate(Unknown Source)
	at io.quarkiverse.googlecloudservices.logging.runtime.cdi.LoggingProducer_ProducerMethod_create_43cdc485b040e9e622e14fa50960c6f67837b748_Bean.create(Unknown Source)
	at io.quarkiverse.googlecloudservices.logging.runtime.cdi.LoggingProducer_ProducerMethod_create_43cdc485b040e9e622e14fa50960c6f67837b748_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkiverse.googlecloudservices.logging.runtime.cdi.LoggingProducer_ProducerMethod_create_43cdc485b040e9e622e14fa50960c6f67837b748_Bean.get(Unknown Source)
	at io.quarkiverse.googlecloudservices.logging.runtime.cdi.LoggingProducer_ProducerMethod_create_43cdc485b040e9e622e14fa50960c6f67837b748_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:485)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:498)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:469)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:227)
	at io.quarkiverse.googlecloudservices.logging.runtime.LoggingHandler.initLogger(LoggingHandler.java:150)
	at io.quarkiverse.googlecloudservices.logging.runtime.LoggingHandler.initGetLogging(LoggingHandler.java:100)
	at io.quarkiverse.googlecloudservices.logging.runtime.LoggingHandler.doPublish(LoggingHandler.java:53)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:[66](https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/4762563265/jobs/8464934801?pr=420#step:6:67))
	at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
	at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:327)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
	at org.jboss.logmanager.Logger.log(Logger.java:[70](https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/4762563265/jobs/8464934801?pr=420#step:6:71)8)
	at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
	at org.jboss.logging.Logger.infof(Logger.java:1125)
	at io.quarkus.bootstrap.runner.Timing.printStartupTime(Timing.java:109)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:2[73](https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/4762563265/jobs/8464934801?pr=420#step:6:74))
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:250)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:592)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:640)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:[84](https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/4762563265/jobs/8464934801?pr=420#step:6:85))
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:[86](https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/4762563265/jobs/8464934801?pr=420#step:6:87))
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:[124](https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/4762563265/jobs/8464934801?pr=420#step:6:125))
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:[126](https://github.com/quarkiverse/quarkus-google-cloud-services/actions/runs/4762563265/jobs/8464934801?pr=420#step:6:127))
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by zanmagerl** [comment]
Hey @zZHorizonZz , do you maybe have a minimal reproducer?
