### ISSUE TITLE
Native Build Fails after Upgrade to Quarkus 3.1.1

### ISSUE THREAD

**Issue by schulzp** [quarkiverse/quarkus-google-cloud-services#450]
Hi!

I recently bumped quarkus from 3.0.0 to 3.1.1. Since then, the native image build fails with the following exception:

```
Fatal error: java.lang.IllegalAccessError: class com.google.api.gax.nativeimage.GoogleJsonClientFeature (in unnamed module @0x393a535) cannot access class com.oracle.svm.core.configure.ResourcesRegistry (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.configure to unnamed module @0x393a535
	at com.google.api.gax.nativeimage.GoogleJsonClientFeature.loadApiClient(GoogleJsonClientFeature.java:76)
	at com.google.api.gax.nativeimage.GoogleJsonClientFeature.beforeAnalysis(GoogleJsonClientFeature.java:55)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

I was able to work around it by passing an additional argument, [see GraalVM ticket](/oracle/graal/issues/5265#issuecomment-1292043045)

```xml
<quarkus.native.additional-build-args>-J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED</quarkus.native.additional-build-args>
```

Is that something that has to be resolved in https://github.com/quarkiverse/quarkus-google-cloud-services or https://cloud.google.com/java/docs/reference/gax/latest/overview?

**Comment by loicmathieu** [comment]
I cannot see how we can resolve it in this extension, it seems to be an issue at the GraalVM native image side.

I need to dig a little deeper, I know Google changed the way they support GraalVM lately.

**Comment by franz-see** [comment]
@schulzp where did you add that additional argument? 😁 thanks!

**Comment by schulzp** [comment]
@loicmathieu, thank you for looking into this! I'll try to contact Google about it.

@franz-see [quarkus-core_quarkus.native.additional-build-args](https://quarkus.io/guides/all-config#quarkus-core_quarkus.native.additional-build-args) is a config option. You may specify it in your application.properties, via environment variable or as maven property inside the native profile:

```xml
<profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>docker.profile</name>
          <value>native</value>
        </property>
      </activation>
      <properties>
        <quarkus.native.container-runtime>docker</quarkus.native.container-runtime>
        <!-- see https://github.com/oracle/graal/issues/5265#issuecomment-1292043045 -->
        <quarkus.native.additional-build-args>-J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED</quarkus.native.additional-build-args>
        <!-- … -->
```

**Comment by schulzp** [comment]
UPDATE: Apparently this has been fixed in newer versions of the `gax` library. The following snippet, requesting the latest version of `com.google.api:gax` has makes the build pass too:

```xml
  <dependencyManagement>
      <!-- … -->
      <dependency>
        <groupId>com.google.api</groupId>
        <artifactId>gax</artifactId>
        <version>2.20.1</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

**Comment by loicmathieu** [comment]
@schulzp I updated the Google libraries, I'll publish a new release for Quarkus 3.2 hope it will fix the issue.

**Comment by loicmathieu** [comment]
@schulzp can you test it with the new release of Google Cloud Services?

**Comment by schulzp** [comment]
@loicmathieu, I can confirm that the native build works with quarkus 3.2.4 and google cloud services 2.1.0. Thank you! 🙇🏻

**Comment by loicmathieu** [comment]
Great! Glad to hear that!
