### ISSUE TITLE
storage: Native image build time error

### ISSUE THREAD

**Issue by zZHorizonZz** [quarkiverse/quarkus-google-cloud-services#525]
When I'm trying to build the native image of quarkus app where I'm using quarkus-google-cloud-storage I'm getting the build time error:
```
========================================================================================================================
GraalVM Native Image: Generating 'hService-0.0.2-SNAPSHOT-2023w45a-runner' (executable)...
========================================================================================================================
Warning: Could not resolve com.google.auth.appengine.AppEngineCredentials for reflection configuration. Reason: java.lang.ClassNotFoundException: com.google.auth.appengine.AppEngineCredentials.
Warning: Could not resolve org.apache.commons.pool2.impl.DefaultEvictionPolicy for reflection configuration. Reason: java.lang.ClassNotFoundException: org.apache.commons.pool2.impl.DefaultEvictionPolicy.
Warning: Could not resolve com.google.protobuf.DescriptorProtos$ExtensionRangeOptions$Declaration for reflection configuration. Reason: java.lang.ClassNotFoundException: com.google.protobuf.DescriptorProtos$ExtensionRangeOptions$Declaration.
Warning: Could not resolve com.google.protobuf.DescriptorProtos$ExtensionRangeOptions$Declaration$Builder for reflection configuration. Reason: java.lang.ClassNotFoundException: com.google.protobuf.DescriptorProtos$ExtensionRangeOptions$Declaration$Builder.
Warning: Could not resolve com.google.protobuf.DescriptorProtos$ExtensionRangeOptions$VerificationState for reflection configuration. Reason: java.lang.ClassNotFoundException: com.google.protobuf.DescriptorProtos$ExtensionRangeOptions$VerificationState.
[1/7] Initializing...                                                                                   (22.6s @ 0.86GB)
 Version info: 'GraalVM 22.3.2 Java 17 CE'
 Java version info: '17.0.7+7-jvmci-22.3-b18'
 C compiler: cl.exe (microsoft, x64, 19.37.32824)
 Garbage collector: Serial GC
 12 user-specific feature(s)
 - com.google.api.gax.grpc.nativeimage.GrpcNettyFeature
 - com.google.api.gax.nativeimage.GoogleJsonClientFeature
 - com.google.api.gax.nativeimage.OpenCensusFeature
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature
 - io.quarkus.hibernate.orm.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - io.quarkus.hibernate.validator.runtime.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.hibernate.validator.internal.util.Version] categories
 - io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - org.eclipse.angus.activation.nativeimage.AngusActivationFeature
 - org.hibernate.graalvm.internal.GraalVMStaticFeature: Hibernate ORM's static reflection registrations for GraalVM
11:45:56,926 WARN  [org.hib.orm.deprecation] HHH90000025: PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[2/7] Performing analysis...  []                                                                        (34.8s @ 3.01GB)
  19,962 (94.44%) of 21,138 classes reachable
  28,478 (64.06%) of 44,453 fields reachable
  95,196 (83.83%) of 113,565 methods reachable
   1,359 classes,     0 fields, and     0 methods registered for reflection
       4 native libraries: crypt32, ncrypt, psapi, winhttp
2 fatal errors detected:
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.grpc.xds.internal.security.TlsContextManagerImpl.releaseServerSslContextProvider(io.grpc.xds.internal.security.SslContextProvider) 
Parsing context:
   at io.grpc.xds.internal.security.TlsContextManagerImpl.releaseServerSslContextProvider(TlsContextManagerImpl.java:90)
   at io.grpc.xds.internal.security.SslContextProviderSupplier.close(SslContextProviderSupplier.java:115)
   at io.grpc.xds.ClusterImplLoadBalancer$ClusterImplLbHelper.updateSslContextProviderSupplier(ClusterImplLoadBalancer.java:285)
   at io.grpc.xds.ClusterImplLoadBalancer$ClusterImplLbHelper.access$300(ClusterImplLoadBalancer.java:173)
   at io.grpc.xds.ClusterImplLoadBalancer.shutdown(ClusterImplLoadBalancer.java:160)
   at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.shutdown(AutoConfiguredLoadBalancerFactory.java:164)
   at io.grpc.internal.ManagedChannelImpl.shutdownNameResolverAndLoadBalancer(ManagedChannelImpl.java:382)
   at io.grpc.internal.ManagedChannelImpl.panic(ManagedChannelImpl.java:844)
   at io.grpc.internal.ManagedChannelImpl$2.uncaughtException(ManagedChannelImpl.java:188)
   at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.trySetException(ForkJoinTask.java:1402)
   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:375)
   at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
   at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
   at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
   at java.lang.reflect.Executable.sharedToString(Executable.java:122)
   at java.lang.reflect.Constructor.toString(Constructor.java:354)
   at java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
   at java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java:408)
   at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializerError(ClassInitializationInfo.java:366)
   at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:359)
   at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:277)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:109)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:562)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.grpc.xds.internal.security.SslContextProvider.getDownstreamTlsContext(). This error is reported at image build time because class io.grpc.xds.internal.security.TlsContextManagerImpl is registered for linking at image build time by command line
	at parsing io.grpc.xds.internal.security.TlsContextManagerImpl.releaseServerSslContextProvider(TlsContextManagerImpl.java:91)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:110)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3393)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3345)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3190)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:84)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:446)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:171)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:349)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
	... 13 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.grpc.xds.internal.security.SslContextProvider.getDownstreamTlsContext(). This error is reported at image build time because class io.grpc.xds.internal.security.TlsContextManagerImpl is registered for linking at image build time by command line
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:333)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:323)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:279)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1721)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5286)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3385)
	... 28 more
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.grpc.xds.internal.security.TlsContextManagerImpl.releaseClientSslContextProvider(io.grpc.xds.internal.security.SslContextProvider) 
Parsing context:
   at io.grpc.xds.internal.security.TlsContextManagerImpl.releaseClientSslContextProvider(TlsContextManagerImpl.java:82)
   at io.grpc.xds.internal.security.SslContextProviderSupplier.close(SslContextProviderSupplier.java:113)
   at io.grpc.xds.ClusterImplLoadBalancer$ClusterImplLbHelper.updateSslContextProviderSupplier(ClusterImplLoadBalancer.java:285)
   at io.grpc.xds.ClusterImplLoadBalancer$ClusterImplLbHelper.access$300(ClusterImplLoadBalancer.java:173)
   at io.grpc.xds.ClusterImplLoadBalancer.shutdown(ClusterImplLoadBalancer.java:160)
   at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.shutdown(AutoConfiguredLoadBalancerFactory.java:164)
   at io.grpc.internal.ManagedChannelImpl.shutdownNameResolverAndLoadBalancer(ManagedChannelImpl.java:382)
   at io.grpc.internal.ManagedChannelImpl.panic(ManagedChannelImpl.java:844)
   at io.grpc.internal.ManagedChannelImpl$2.uncaughtException(ManagedChannelImpl.java:188)
   at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.trySetException(ForkJoinTask.java:1402)
   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:375)
   at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
   at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
   at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
   at java.lang.reflect.Executable.sharedToString(Executable.java:122)
   at java.lang.reflect.Constructor.toString(Constructor.java:354)
   at java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
   at java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java:408)
   at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializerError(ClassInitializationInfo.java:366)
   at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:359)
   at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:277)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:109)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:562)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
------------------------------------------------------------------------------------------------------------------------
```

**Comment by zZHorizonZz** [comment]
Hi,

I have looked into it, and creating a reproducer will probably require more time than I expected. It doesn't work in my main project, but in the test project, it seems like it's working. I will try to make time before the year's end for this.

**Comment by loicmathieu** [comment]
This typically occurs if you have a combination of extensions that triggers the native issue (by the way, if it also has the logging extension I just fixed an issue for native but the stacktrace seems different). Or if you use more of the API than in the reproducer.

**Comment by loicmathieu** [comment]
I you use any library that is not a Quarkus extension, it can brings GraalVM native image issues that are totally unrelated to Quarkus and that we cannot do anything about.
That's why we always need a reproducer ;)
