### ISSUE TITLE
Firestore cannot be injected if using the emulator

### ISSUE THREAD

**Issue by huw0** [quarkiverse/quarkus-google-cloud-services#54]
If `FIRESTORE_EMULATOR_HOST` environment variable is set a stracktrace is thrown because Quarkus still attempts to resolve Cloud Credentials.

```
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
        at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:134)
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:119)
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:91)
        at io.quarkiverse.googlecloudservices.common.GcpCredentialProducer.googleCredential(GcpCredentialProducer.java:30)
        at io.quarkiverse.googlecloudservices.common.GcpCredentialProducer_ProducerMethod_googleCredential_f50c1039bd62c63834aaa61a686a2c22210490cc_Bean.create(GcpCredentialProducer_ProducerMethod_googleCredential_f50c1039bd62c63834aaa61a686a2c22210490cc_Bean.zig:201)
```

Emulator can be used if creating the Firestore object with

```
FirestoreOptions.getDefaultInstance().getService();
```

**Comment by huw0** [comment]
With the above, there is another error at the point where a firestore request is actually made. Possibly, the issue can be resolved by updating the firestore dependency to 2.1.0?

**Comment by huw0** [comment]
Still issues with latest 2.1.0. Probably this is a gcloud library issue
https://github.com/googleapis/java-firestore/issues/361

**Comment by loicmathieu** [comment]
@huw0 to use the emulator in a test, you need to mock the `GcpCredentials` object as there is a CDI producer that creates even if an emulator is used.

You can find and example here: https://github.com/quarkiverse/quarkiverse-google-cloud-services/blob/master/integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/mock/GcpCredentialProducerMock.java

Maybe this needs to be documented, or maybe we can add a `use-emulator` config property that will automatically mock (or create an empty credential) if set.
