### ISSUE TITLE
When I use CollectionReference.add in Firestore, native build fails

### ISSUE THREAD

**Issue by somen440** [quarkiverse/quarkus-google-cloud-services#97]
pom.xml

```xml
...
    <dependency>
      <groupId>io.quarkiverse.googlecloudservices</groupId>
      <artifactId>quarkus-google-cloud-firestore</artifactId>
      <version>0.5.0</version>
    </dependency>
...
```

Java code

```java
...
    var ref = firestore.collection(collectionName);

    var pojo = new HashMap<>();
    pojo.put("name", name);
    pojo.put("description", description);

    ref.add(pojo);
...
```

`./mvnw package -Pnative`

```shell
...
...
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Detailed message:
Trace: Object was reached by 
        reading field java.security.SecureRandom.secureRandomSpi of
                constant java.security.SecureRandom@266ec2cd reached by 
        scanning method com.google.cloud.firestore.FirestoreImpl.autoId(FirestoreImpl.java:84)
Call path from entry point to com.google.cloud.firestore.FirestoreImpl.autoId(): 
        at com.google.cloud.firestore.FirestoreImpl.autoId(FirestoreImpl.java:81)
        at com.google.cloud.firestore.CollectionReference.document(CollectionReference.java:103)
        at com.google.cloud.firestore.CollectionReference.add(CollectionReference.java:194)
        at com.google.cloud.firestore.CollectionReference.add(CollectionReference.java:222)
```

I solved this in the following way ...

```diff
     var data = new HashMap<>();
     data.put("name", name);
     data.put("description", description);
 
-    var result = collectionRef.add(data);
+    var id = UUID.randomUUID().toString();
+    collectionRef.document(id).set(data);
```

Is there a better solution to this problem?

---

Reference link

- https://github.com/ballerina-platform/ballerina-standard-library/issues/75

**Comment by loicmathieu** [comment]
Duplicated with #90

This is fixed in master, I'll release version 0.6 soon that will fix the issue.
I you can build this repo from master and try the fix and provide feedback this would be great!

Otherwise, I'll close it as it seems to be the same as #90 and already fixed.

**Comment by somen440** [comment]
Thank you for your prompt reply!
I tried the solution but got the following error ...

change diff

```diff
...
+  <parent>
+    <groupId>io.quarkiverse.googlecloudservices</groupId>
+    <artifactId>quarkus-google-cloud-services-parent</artifactId>
+    <version>0.6.0-SNAPSHOT</version>
+    <relativePath>../quarkus-google-cloud-services/pom.xml</relativePath>
+  </parent>
   <modelVersion>4.0.0</modelVersion>
...
...
     <dependency>
       <groupId>io.quarkiverse.googlecloudservices</groupId>
       <artifactId>quarkus-google-cloud-firestore</artifactId>
-      <version>0.5.0</version>
+      <version>0.6.0-SNAPSHOT</version>
     </dependency>
```

error message

```shell
Could not find artifact io.quarkiverse.googlecloudservices:quarkus-google-cloud-firestore:jar:0.6.0-SNAPSHOT -> [Help 1]
```

What's wrong with this?

**Comment by loicmathieu** [comment]
Yes, snapshots are not deployed nightly, you need to clone the repo and build locally (via mvn clean install).
I'll release 0.6 soon so no hurry

**Comment by somen440** [comment]
thx!!!!
`mvn clean install` as advised and it passed the build.

**Comment by loicmathieu** [comment]
Thanks for the feedback, I'm closing it now, 0.6 should be release today I hope
